### ISSUE TITLE
Improve `size_hint` upper bound

### ISSUE THREAD

**Issue by RunDevelopment** [andrewhickman/iter-set#1]
The `intersection*` and `difference*` functions are implemented using `filter_map`. This method returns a [`FilterMap` iterator](https://doc.rust-lang.org/std/iter/struct.FilterMap.html) that implements `size_hint` like [this](https://doc.rust-lang.org/src/core/iter/adapters/filter_map.rs.html#65):

```rs
    #[inline]
    fn size_hint(&self) -> (usize, Option<usize>) {
        let (_, upper) = self.iter.size_hint();
        (0, upper) // can't know a lower bound, due to the predicate
    }
```

This means that the upper bound for the above-mentioned functions is that of `Classify` which is [roughly](https://github.com/andrewhickman/iter-set/blob/445ac23b3e0f26c36d140fae13ad50a885384c25/src/lib.rs#L533) `left.upper_bound + right.upper_bound`.

While correct, the upper bound can be improved. For the above-mentioned functions the upper bounds should ideally be:

- `intersection`: `min(left.upper_bound, right.upper_bound)`
- `difference`: `left.upper_bound`

**Comment by andrewhickman** [comment]
Good spot, would be nice to provide a better hint. A PR would be welcome

I'm curious if you're using the upper bound for anything? I don't think I've every actually seen it used

**Comment by RunDevelopment** [comment]
> A PR would be welcome

Sure think, I'll make one.

> I'm curious if you're using the upper bound for anything? I don't think I've ever actually seen it used

TBH, I'm not using it either. I'm building an in-memory inverted index and needed something to score post lists. While searching for that something, I noticed that the upper bound was too high.
